handle evdev.InputDevice failures
evdev.InputDevice(...) may fail with

  OSError: [Errno 25] Inappropriate ioctl for device

for some devices that have the ID_INPUT_KEYBOARD bit set,
for example a modern logitech unified receiver.

log a warning and ignore the device instead of crashing.